### ISSUE TITLE
Opacity vs Transparency confusion

### ISSUE THREAD

**Issue by bhouston** [DassaultSystemes-Technology/EnterprisePBRShadingModel#12]
Material models generally differentiate between Opacity and Transparency and there is a use for both.

Does the EPBR model currently support Opacity?

Just to be completely clear, Opacity usually refers to the material as a whole and its interaction with light.  When you adjust opacity one usually causes the material to fade out completely, this includes both the clear coat, specular lobe, diffuse layer and the transmission layer.

This is admittedly non-physical but it is actually critical in practical visual applications -- otherwise how do you fade in an object that has a specular/reflective component.  If you do not have this you need to do a complex adjustment on the specular components in time with the transmission value to achieve smooth fading.

Transparency by contrast refers to the opacity of just the diffuse layer and how much the transmission layer can leak through.  Thus transparency is a restricted form of opacity.

In this material model, do you have an equivalency of opacity or just transparency?  Maybe if you really do not want opacity because it is non-physical, there should be a note to that effect in the specification.

**Comment by proog128** [comment]
Thanks for the detailed feedback! We will probably need some time to digest it, but as a quick answer to this issue: we support transparency and opacity. The parameter to control opacity is called [cut-out opacity](https://dassaultsystemes-technology.github.io/EnterprisePBRShadingModel/spec.md.html#components/cut-out).

Transparency is the physically-based effect that results from sampling a BTDF, including roughness and anisotropy.

Cut-Out Opacity serves two purposes:

1. It adds detail to (thin-walled) geometry. In this case, the value is either 0 or 1.
2. It makes the surface (semi-)transparent, independent of the BSDFs. If I am not mistaken, this is the effect you are looking for.

**Comment by bhouston** [comment]
Ah, yes.  You are correct, your "Cutout" opacity parameter is like a classic opacity parameter.

I would just call it Opacity as I got confused by the focus on the name "Cutout".

Did you know that "Cutout" opacity usually refers to 0/1 opacity values resulting from a comparison of the alpha map with a user specified alphaTreshold?  I suggest that your parameter is misnamed.

Marmoset: For example the use of the term "Cutout" in Marmoset tool bag means that things are either 1 or 0 if the alpha is about the Cutout threshold: https://polycount.com/discussion/133507/marmoset-transparent-opaque-issues

Unity: In Unity it describes Cutout as a special mode in this way: "Cutout - Allows you to create a transparent effect that has hard edges between the opaque and transparent areas. In this mode, there are no semi-transparent areas, the texture is either 100% opaque, or invisible. This is useful when using transparency to create the shape of materials such as leaves, or cloth with holes and tatters."  https://docs.unity3d.com/Manual/StandardShaderMaterialParameterRenderingMode.html  https://docs.unity3d.com/Manual/shader-TransparentCutoutFamily.html

Sketchfab: In the Sketchfab documentation they describe using alpha with a threshold as an 0 / 1 mask as achieving a "Cutout" effect.  "ou can use the slider to set an Alpha "Threshold". Masking is useful for materials that require a "cutout" effect like leaves and logos."  https://help.sketchfab.com/hc/en-us/articles/202602073-Transparency-Opacity#mask

And our own Clara.io uses this terminology.

So describing Opacity as "Cutout Opacity" is confusing and I believe incorrect based on standard industry naming conventions.

**Comment by proog128** [comment]
The main use-case for this parameter is actually the Boolean cut-out as you describe. Using it as opacity has some caveats in ray tracers, if possible the physically-based transparency is favored.

We based the parameter on the definition in MDL, see [MDL Handbook, The material_geometry struct](http://mdlhandbook.com/mdl_handbook/index.html#geometry#the-material-geometry-struct).

**Comment by bhouston** [comment]
ray tracers also have this distinction and model opacity either as a grayscale or as a threshold/mask/cutout.

Arnold has opacity and refraction (e.g. transmission) as I am suggesting: https://docs.arnoldrenderer.com/display/AFMUG/Refraction+And+Opacity

V-Ray also has opacity that is separate from its refraction (e.g. transmission) parameter: https://docs.chaosgroup.com/display/VRAY3MAX/V-Ray+Material+%7C+VRayMtl#V-RayMaterial|VRayMtl-opacityModeParameter

**Comment by bhouston** [comment]
My recommendation is that you call this opacity and there is another value called opacity_cutout that defaults to -1 (meaning interpret opacity as smooth), and if it is in the range of 0-1 it is the cutout threshold and it forces opacity to be either 0 or 1.  This achieves both effects and clarifies when it is interpreted as a cutout.
