### ISSUE TITLE
Typo in Fresnel multi-scattering formula

### ISSUE THREAD

**Issue by shermnonic** [DassaultSystemes-Technology/EnterprisePBRShadingModel#18]
There seems to be a typo in the first definition given for F_{m,avg} in both 2020.x and 2021.x spec. That is, if I assume correctly that f_0 corresponds to \rho_{s,r,0} and f_{90} to \rho_{s,r,90}. Under this assumption it seems that f_0 and f_{90} should be switched in the first of the following two equations:

* F_{m,avg}(f_0, f_{90}) &=& \frac{1}{21} f_0 + \frac{20}{21} f_{90}
* F_{m,avg} &=& \frac{1}{21} \rho_{s,r,90} + \frac{20}{21} \rho_{s,r,0}

Those are equations (33) and (71) in sections 1.1.5.3 and 5.2.1 of the the 2020.x spec respectively.

The second equation agrees with multi-scattering literature (e.g. Fdez-Agüera, JCGT 2019).

**Comment by proog128** [comment]
Fixed it, thank you!
