### ISSUE TITLE
Live demo and metals with KHR_materials_clearcoat?

### ISSUE THREAD

**Issue by echadwick-artist** [DassaultSystemes-Technology/EnterprisePBRShadingModel#26]
1. https://dassaultsystemes-technology.github.io/dspbr-pt/
2. Load attached model. [Clearcoat-Metals-Test-GLB.zip](https://github.com/DassaultSystemes-Technology/EnterprisePBRShadingModel/files/7907284/Clearcoat-Metals-Test-GLB.zip)

Result: the spheres in the top row do not show colored metal underneath clearcoat.

![image](https://user-images.githubusercontent.com/40177036/150389939-c230c22c-316d-4d96-b853-3298f039cea1.png)

Top row: colored metals with KHR_materials_clearcoat.
2nd row: colored metals without clearcoat.
3rd row: colored dielectrics with KHR_materials_clearcoat.
4th row: colored dielectrics without clearcoat.

Thanks!

By the way, the live demo is an excellent resource for glTF materials work, as a raytraced source of truth. Thank you for providing thiss important resource!

**Comment by bsdorra** [comment]
@echadwick-wayfair sorry for the unresponsiveness, I somehow missed the notifcation for this issue. I updated the demo viewer with a fix. Happy to hear that you find the project useful, thanks for the feedback!
