### ISSUE TITLE
Displacement 

### ISSUE THREAD

**Issue by bhouston** [DassaultSystemes-Technology/EnterprisePBRShadingModel#6]
(I really like your work.  It is similar to a document I worked on back in 2015 with a bit of input from Nick Porcino (who created Apple's material specification) and a tiny bit from Brent Burley (of Disney PBR): https://docs.google.com/document/d/1EUqnM-aQwl76aZpduQk-EL0vGEPHrJE7h1x7wSqqLlk/edit# )

We would like to adopt your specification but we need a few very important changes.  There are a few things missing from your specification to make it complete.  I will make an issue for each one.

The first issue is displacement.  Displacement (scalar or vector) is also really nice to have, at least the option of it. It is hard to support properly in WebGL because of the inability to do GPU-based tessellation but hopefully that changes at some point.  But every other engine can support real-time tessellation and it is shame to lose it.  I would suggest supporting vector displacement rather than both scalar and vector.  It is easy to create a single gray scale jpeg if you want just want scalar displacement.

**Comment by bhouston** [comment]
FYI Tobias from Dassault responded in a different forum: "A vector displacement parameter would be a nice addition to the material model."

**Comment by proog128** [comment]
In version 2021x, we now support vector displacement. Thanks for the suggestion!
